# Generated by Django 5.2.6 on 2025-10-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_aiusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
