# Generated by Django 5.2.6 on 2025-10-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
