# Generated by Django 5.2.6 on 2025-10-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_article_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusage",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_usage",
                to="articles.article",
            ),
        ),
        migrations.AlterField(
            model_name="aiusage",
            name="estimated_cost",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
